services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    ports:
      - '0.0.0.0:80:80'
      - '[::]:80:80'
      - '0.0.0.0:443:443'
      - '[::]:443:443'
    volumes:
      - /var/data/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/data/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /var/data/traefik/certs:/letsencrypt
    env_file: .env
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`nginx.tbs.amn.gg`) || Host(`traefik.tailscale.amn.gg`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=porkbun

  newt:
    image: docker.io/fosrl/newt
    container_name: newt
    restart: unless-stopped
    env_file: .env
    command:
      - -endpoint
      - https://pangolin.manko.yoga
    networks:
      - public

networks:
  public:
    external: true
    name: public
